### ISSUE TITLE
Mirror not updated for about 8 days now

### ISSUE THREAD

**Issue by sdelafond** [mirror/dd-wrt#22] opened 2016-12-21 09:12 UTC
See http://svn.dd-wrt.com/timeline for recent changes.

**Comment by jkldgoefgkljefogeg** [comment] 2016-12-21 09:30
Thanks for the heads up. After a migration some files got "dirty", I will see if this happens again. Never figured out what the cause was.

`$ git svn rebase
src/router/openvpn/src/compat/compat.vcxproj: needs update
src/router/openvpn/src/compat/compat.vcxproj.filters: needs update
src/router/openvpn/src/openvpn/openvpn.vcxproj: needs update
src/router/openvpn/src/openvpn/openvpn.vcxproj.filters: needs update
src/router/openvpn/src/openvpnserv/openvpnserv.vcxproj: needs update
update-index --refresh: command returned error: 1


$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/router/openvpn/src/compat/compat.vcxproj
        modified:   src/router/openvpn/src/compat/compat.vcxproj.filters
        modified:   src/router/openvpn/src/openvpn/openvpn.vcxproj
        modified:   src/router/openvpn/src/openvpn/openvpn.vcxproj.filters
        modified:   src/router/openvpn/src/openvpnserv/openvpnserv.vcxproj

no changes added to commit (use "git add" and/or "git commit -a")`

**Comment by sdelafond** [comment] 2016-12-21 09:31
Very weird, especially in a "read-only" clone like the one you're maintaining. I've never seen that before either.

**Comment by jkldgoefgkljefogeg** [comment] 2016-12-22 00:39
No more issue so far.

**Closed** 2016-12-24 14:16 UTC
